name: "OpenAI PR Reviewer"
description: "Post an AI code review comment on pull requests using OpenAI"
author: "Tom Stirrop-Metcalfe"
branding:
  icon: "message-square"
  color: "blue"

inputs:
  openai_api_key:
    description: "OpenAI API key"
    required: false
  model:
    description: "OpenAI model id"
    required: false
    default: "gpt-4.1-mini"
  max_chars:
    description: "Approx max characters of patch to send"
    required: false
    default: "120000"
  category_style:
    description: "Review style: default|strict"
    required: false
    default: "default"
  dry_run:
    description: "If true, skip OpenAI and posting comment; output preview instead"
    required: false
    default: "false"
  pr_number:
    description: "PR number to operate on (for workflow_dispatch/manual runs)"
    required: false

outputs:
  review_body:
    description: "The generated review body (preview in dry_run)"

runs:
  using: node20
  main: dist/index.js