name: Verify dist is up-to-date

on:
  pull_request:
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  verify-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build action
        run: npm run build

      - name: Fail if dist changed
        run: |
          CHANGED=$(git status --porcelain -- dist | wc -l)
          if [ "$CHANGED" -ne 0 ]; then
            echo "dist/ is not up to date. Run 'npm run build' and commit the updated dist files." >&2
            echo "Changed files:" >&2
            git --no-pager status --porcelain -- dist >&2
            exit 1
          fi